export enum Ng2AnimationType {
  NONE = 'NONE',
  FADE_IN = 'FADE_IN',
  FADE_IN_LEFT = 'FADE_IN_LEFT',
  FADE_IN_RIGHT = 'FADE_IN_RIGHT',
  ZOOM_IN = 'ZOOM_IN',
  CARD_IN_LEFT = 'CARD_IN_LEFT',
  CARD_IN_RIGHT = 'CARD_IN_RIGHT',
}