export * from './app/ngx-carousel/ngx-carousel.module'
export * from './app/models/ngx-carousel-item.model'
export * from './app/models/ngx-carousel-setting.model'
export * from './app/models/ngx-carousel-animation-type.model'
export * from './app/ngx-carousel/ngx-carousel.component'